# Communication channel: "SimpleChannelUDP" for using udp
string channel
# IP address of the force feedback device 
string ff_device_ip_address
# Param file to be used for the force feedback device
string ff_device_param_file
# Ip address of the device where the raptor api node is running
string local_ip_address

# Automatic calibration
# True for automatic, False for manual
bool automatic

---

# Success
bool success

# Errors
# True if error occurred
bool already_calibrated
bool hardware_down
bool timeout

